#
# Copyright 2014 Freescale Semiconductor, Inc.
#
# SPDX-License-Identifier:      GPL-2.0+
#

obj-$(CONFIG_NAI6XPPC2) += board.o
obj-$(CONFIG_NAI6XPPC2) += eth.o
obj-$(CONFIG_NAI6XPPC2) += cpld.o
obj-$(CONFIG_PCI)       += pci.o
obj-y   += cmd_pci_dma.o

obj-y   += ddr.o
obj-y   += law.o
obj-y   += tlb.o
