#
# Copyright 2014 Freescale Semiconductor, Inc.
#
# SPDX-License-Identifier:      GPL-2.0+
#

obj-$(CONFIG_NAI68PPC2) += nai68ppc2.o
obj-$(CONFIG_NAI68PPC2) += eth_nai68ppc2.o
obj-$(CONFIG_NAI68PPC2) += cpld.o
obj-$(CONFIG_PCI)       += pci.o

obj-y   += ddr.o
obj-y   += law.o
obj-y   += tlb.o
